name: kbmap

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # only for CI environment
      # use issue #8 solution instead
      - name: 'open uinput for writing'
        run: sudo chmod 777 /dev/uinput

      - name: install
        run: pip install .

      - name: test
        run: python -m unittest -v

      - name: install coverage
        run: pip install coverage

      - name: code coverage
        run: coverage run -m unittest

      - name: install codecov
        run: pip install codecov

      - name: upload coverage to codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

